DATA_FILE_SUFFIX=".tfrecord.gz"
FEATURE_COLUMNS=["visibility"]
LABEL_COLUMN="snow_depth"
RAW_METADATA_DIR="raw_metadata"
TRANSFORM_FN_DIR="transform_fn"
TRANSFORMED_EVAL_DATA_FILE_PREFIX="eval"
TRANSFORMED_METADATA_DIR="transformed_metadata"
TRANSFORMED_TRAIN_DATA_FILE_PREFIX="train"
